version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Composer"
      include: "scope"
    versioning-strategy: increase-if-necessary
    groups:
      drupal-core:
        patterns:
          - "drupal/core*"
      drupal-projects:
        patterns:
          - "drupal/*"
        exclude-patterns:
          - "drupal/core*"
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/web/themes/custom/contribtracker/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "npm"
    groups:
      types:
        patterns:
          - "@types/*"
      linters:
        patterns:
          - "eslint*"
          - "stylelint*"
          - "@typescript-eslint/*"
      percy:
        patterns:
          - "@percy/*"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "github-actions"
