#!/bin/bash
## Description: Use Cypress in "runner" mode.
##
## Usage: cypress-run [arguments]
## Example: "ddev cypress-run"
## This executes only the functional test cases using Electron.

# We set the default CYPRESS_ADMIN_USERNAME and CYPRESS_ADMIN_PASSWORD
# in `docker-composer.cypress.yaml`. On command-line environments where
# this is not set, reset your admin password using drush like so:
# `ddev drush upwd ct-admin ct-admin`
DISPLAY= cypress run "$@"
