#!/bin/bash
# Description: Use Cypress in "runner" mode with Percy for visual testing.
#
# The DISPLAY environment variable is unset to allow tests to run in an environment without a display (e.g., for headless browsers).
# This script runs visual regression tests using Percy integrated with Cypress.
# `npm run vr` executes `percy exec -- cypress run` as defined in package.json.
# Percy is not available globally on the Cypress image, hence we use the local version specified in the package.json.

## Usage: percy-run
## Example: "ddev percy-run"

DISPLAY= npm run vr
