name: CIGrumPHP
on:
  push:
    branches:
      - cicdtest
    tags:
      - '*'
  pull_request:

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  drupal_codequality:
    runs-on: ubuntu-latest
    container: hussainweb/drupalqa
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Enable GrumPHP plugin
        run: composer global config --no-plugins allow-plugins.phpro/grumphp-shim true

      - name: Install GrumPHP globally
        run: composer global require phpro/grumphp-shim

      # Run each checks separately
      # - name: Run phplint
      #   run: grumphp run --tasks=phplint
      # - name: Run phpcs
      #   run: grumphp run --tasks=phpcs
      # - name: Run phpmd
      #   run: grumphp run --tasks=phpmd

      # Run using testsuites
      # - name: Run linters
      #   run: grumphp run --testsuite=linters
      # - name: Run code quality check
      #   run: grumphp run --testsuite=code_quality

      # Try running phpstan without composer as current ruleset only checks for drupal standard
      - name: Run phptan
        run: grumphp run --tasks=phpstan

