name: Clean Platform.sh env on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  on-pr-close:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean Platform.sh env if available
        uses: "./.github/actions/platformsh-clean-env"
        with:
          project-id: "brbqplxd7ycq6"
          cli-token: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
