name: Playwright Tests

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday midnight

jobs:
  playwright_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: Set the platform.sh token
        run: |
          ddev config global --web-environment-add="PLATFORMSH_CLI_TOKEN=${{ secrets.PLATFORMSH_CLI_TOKEN }}"
          ddev start

      - name: Install dependencies
        run: |
          ddev composer install
          ddev pull platform -y
          cd web/themes/custom/contribtracker
          npm ci --prefer-offline --no-audit

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'test/playwright/package-lock.json'

      - name: Install Playwright
        run: |
          cd test/playwright
          npm ci --prefer-offline --no-audit
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd test/playwright
          npm run test

      - name: Save playwright report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: |
            test/playwright/playwright-report
            test/playwright/tests/visual
          retention-days: 3
